


use mp3;

DROP TABLE POST;
DROP TABLE SONG;
DROP TABLE GENRE;

use mp3;
CREATE TABLE POST (
  PID INT(10) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(100) NOT NULL,
  CONTENT VARCHAR(1000) NOT NULL,
  U_ID VARCHAR(20),
  U_PW VARCHAR(20),
  COMPLETED CHAR(1) NOT NULL DEFAULT 'N',
  DELETED CHAR(1) NOT NULL DEFAULT 'N',
  COUNT INT(2),
  CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED DATETIME,
  PRIMARY KEY (PID)
);

CREATE TABLE GENRE (
  GID INT(2) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(20) NOT NULL,
  PRIMARY KEY (GID)
);

CREATE TABLE SONG(
  SID INT(4) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(50) NOT NULL,
  ARTIST VARCHAR(50) NOT NULL,
  ALBUM VARCHAR(50) NOT NULL,
  LYRICS VARCHAR(2000) NOT NULL,
  V_URL VARCHAR(300) NOT NULL,
  IMG_URL VARCHAR(300) NOT NULL,
  IMG_PATH VARCHAR(300) NOT NULL,
  COUNT INT(2),
  S_GID INT,
  FOREIGN KEY (S_GID) REFERENCES GENRE(GID),
  PRIMARY KEY (SID)
);

-- use TEST;

-- INSERT INTO GENRE(TITLE) VALUES("POP");
-- INSERT INTO GENRE(TITLE) VALUES("R&B/SOUL");
-- INSERT INTO GENRE(TITLE) VALUES("DANCE");
-- INSERT INTO GENRE(TITLE) VALUES("RAP/HIPHOP");
-- INSERT INTO GENRE(TITLE) VALUES("INDI");
-- INSERT INTO GENRE(TITLE) VALUES("ROCK/METAL");
-- INSERT INTO GENRE(TITLE) VALUES("TROT");
-- INSERT INTO GENRE(TITLE) VALUES("PORT/BLUES");
-- INSERT INTO GENRE(TITLE) VALUES("SINGER SONGWRITER");
-- INSERT INTO GENRE(TITLE) VALUES("BALLAD");